create table if not exists public.quote_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  phone text not null,
  location text not null,
  service text not null,
  message text not null,
  source text not null default 'website'
);

alter table public.quote_requests enable row level security;

drop policy if exists "Allow public quote inserts" on public.quote_requests;
create policy "Allow public quote inserts"
on public.quote_requests
for insert
to anon, authenticated
with check (true);

grant usage on schema public to anon, authenticated;
grant insert on table public.quote_requests to anon, authenticated;
